# Debug mode settings
debug:
  enabled: false
  log-level: INFO # DEBUG, INFO, WARNING, ERROR

# General settings
general:
  override-e-key: true # Whether to override the default inventory key (E)

# Armor slots (fixed positions)
armor-slots:
  helmet: 0
  chestplate: 9
  leggings: 18
  boots: 27

# Custom slots configuration
# Lore Format <form>: <type>
custom-slots:
  slots:
    '0':
      enabled: true
      slot-type: attribute
      form: Type
      type: Ring
      position: 2
      lore_match: 'Type: Ring'
    '1':
      enabled: true
      slot-type: attribute
      form: Type
      type: Ring
      position: 3
      lore_match: 'Type: Ring'
    2:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Bracelet"
      position: 11
      lore_match: "Type: Bracelet"
    3:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Relic"
      position: 12
      lore_match: "Type: Relic"
    4:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Talisman"
      position: 20
      lore_match: "Type: Talisman"
    5:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Charm"
      position: 21
      lore_match: "Type: Charm"
    6:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Medallion"
      position: 29
      lore_match: "Type: Medallion"
    7:
      enabled: false
      slot-type: "attribute"
      form: "Type"
      type: "Trinket"
      position: 30
      lore_match: "Type: Trinket" 